'use client';
import React, { useState } from "react";
import { Receipt, Landmark, PlusCircle, Download } from "lucide-react";
import { useVendorPayments } from "@/hooks/use-dashboard";
import { adaptPaymentInvoices } from "@/lib/elite-adapters";
import { toast } from "sonner";

export function PaymentsReceivedView() {
  const { data: paymentsData } = useVendorPayments(1, 50);
  const invoices = adaptPaymentInvoices(paymentsData?.payments || []);

  const [showForm, setShowForm] = useState(false);
  
  // Invoice form states
  const [clientName, setClientName] = useState("");
  const [amount, setAmount] = useState("");
  const [dueDate, setDueDate] = useState(new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().substring(0, 10));

  const handleCreateInvoice = (e: React.FormEvent) => {
    e.preventDefault();
    if (!clientName || !amount) return;

    toast.success(`Invoice for ${clientName} generated. Note: Invoices are usually auto-generated by the platform.`);

    // Reset Form
    setClientName("");
    setAmount("");
    setShowForm(false);
  };

  const statusColors = {
    Paid: "bg-green-50 text-green-700 border-green-200 font-bold",
    Unpaid: "bg-blue-50 text-blue-700 border-blue-200",
    Overdue: "bg-rose-50 text-rose-700 border-rose-200 font-bold animate-pulse",
  };

  const totalPaid = paymentsData?.total || 0;
  const totalPending = 0; // The API only returns total received for now

  return (
    <div className="space-y-8">
      {/* Upper Context Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h2 className="text-3xl font-bold text-on-surface tracking-tight">Payments Received</h2>
          <p className="text-sm text-secondary font-medium">Manage incoming client invoices, routing numbers &amp; wire details.</p>
        </div>

        <button
          onClick={() => setShowForm(!showForm)}
          className="flex items-center gap-2 px-5 py-2.5 bg-primary-container text-white text-xs font-bold rounded-full shadow-lg shadow-primary/20 hover:bg-primary transition-all duration-150 cursor-pointer self-start md:self-auto"
        >
          <PlusCircle className="w-4 h-4" />
          {showForm ? "Collapse Invoicing Desk" : "Generate Billing Invoice"}
        </button>
      </div>

      {/* Dynamic Slide Drawer Form */}
      {showForm && (
        <form onSubmit={handleCreateInvoice} className="p-6 bg-white/80 border border-gray-100 rounded-2xl space-y-4 shadow-sm animate-fade-in-up">
          <h3 className="text-sm font-bold text-on-surface uppercase tracking-wider">Draw Client Billing Ledger</h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="space-y-1">
              <label className="text-[10px] font-bold text-secondary uppercase block">Client Corporate Title</label>
              <input
                type="text"
                required
                placeholder="e.g. Acme Corporate Ventures LLC"
                value={clientName}
                onChange={(e) => setClientName(e.target.value)}
                className="w-full h-10 px-3 bg-gray-50 border border-gray-200 rounded-xl focus:border-primary-container outline-none text-xs"
              />
            </div>

            <div className="space-y-1">
              <label className="text-[10px] font-bold text-secondary uppercase block">Invoice Amount (₹)</label>
              <input
                type="number"
                step="0.01"
                required
                placeholder="2500"
                value={amount}
                onChange={(e) => setAmount(e.target.value)}
                className="w-full h-10 px-3 bg-gray-50 border border-gray-200 rounded-xl focus:border-primary-container outline-none text-xs"
              />
            </div>

            <div className="space-y-1">
              <label className="text-[10px] font-bold text-secondary uppercase block">Due Date Deadline</label>
              <div className="flex gap-4">
                <input
                  type="date"
                  required
                  value={dueDate}
                  onChange={(e) => setDueDate(e.target.value)}
                  className="flex-1 h-10 px-3 bg-gray-50 border border-gray-200 rounded-xl focus:border-primary-container outline-none text-xs"
                />
                <button
                  type="submit"
                  className="px-6 h-10 bg-primary-container text-white font-bold text-xs rounded-xl shadow-md hover:bg-primary transition-all cursor-pointer"
                >
                  Create List
                </button>
              </div>
            </div>
          </div>
        </form>
      )}

      {/* Statistics and active payout bank settings */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="glass-card rounded-2xl p-5 border-l-4 border-l-green-600">
          <span className="text-[10px] font-bold text-secondary uppercase tracking-widest block">Invoiced: Settled Credits</span>
          <p className="text-2xl font-bold font-mono text-on-surface mt-1">₹{totalPaid.toLocaleString(undefined, { minimumFractionDigits: 2 })}</p>
        </div>

        <div className="glass-card rounded-2xl p-5 border-l-4 border-l-blue-600">
          <span className="text-[10px] font-bold text-secondary uppercase tracking-widest block">Invoiced: Outstanding Debits</span>
          <p className="text-2xl font-bold font-mono text-on-surface mt-1">₹{totalPending.toLocaleString(undefined, { minimumFractionDigits: 2 })}</p>
        </div>

        <div className="glass-card rounded-2xl p-5 flex items-center justify-between">
          <div>
            <span className="text-[10px] font-bold text-secondary uppercase tracking-widest block">Payout Routing</span>
            <span className="text-sm font-bold text-on-surface inline-block mt-1">Direct Bank Wire</span>
          </div>
          <Landmark className="w-5 h-5 text-primary-container" />
        </div>
      </div>

      {/* Live Invoices table board */}
      <div className="glass-panel rounded-2xl p-6">
        <div className="flex justify-between items-center mb-6">
          <div>
            <h3 className="text-lg font-bold text-on-surface font-sans">Payment Invoices</h3>
            <p className="text-xs text-secondary">Dynamic corporate accounts, receipt dates &amp; collection states.</p>
          </div>
          <span className="text-xs font-mono text-secondary">Export options live</span>
        </div>

        <div className="space-y-4">
          {invoices.map((inv) => (
            <div
              key={inv.id}
              className="p-4 bg-white/60 hover:bg-white border border-gray-100 rounded-xl flex flex-col md:flex-row md:items-center md:justify-between gap-4 transition-all"
            >
              <div className="flex items-center space-x-4">
                <div className="w-10 h-10 rounded-full bg-primary/5 text-primary-container flex items-center justify-center">
                  <Receipt className="w-4.5 h-4.5 text-primary-container" />
                </div>

                <div>
                  <h4 className="text-sm font-bold text-on-surface">{inv.clientName}</h4>
                  <div className="flex items-center gap-2 text-xs text-secondary mt-0.5 font-mono">
                    <span className="text-primary font-bold">{inv.invoiceNumber}</span>
                    <span>•</span>
                    <span>Issued: {inv.issueDate}</span>
                    <span>•</span>
                    <span>Due: {inv.dueDate}</span>
                  </div>
                </div>
              </div>

              <div className="flex items-center gap-4 self-end md:self-auto">
                <div className="text-right">
                  <span className="text-sm font-bold text-primary-container font-mono">
                    ₹{inv.amount.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                  </span>
                </div>

                <span className={`px-3 py-1 border text-[10px] font-bold rounded-full ${statusColors[inv.status]}`}>
                  {inv.status}
                </span>
                
                <button
                  className="p-1.5 hover:bg-gray-100 rounded-lg text-secondary"
                  title="Download CSV Statement"
                  onClick={() => toast.success(`Exporting statement ${inv.invoiceNumber} in CSV format.`)}
                >
                  <Download className="w-4 h-4 text-secondary" />
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
